// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/cache/cache.proto

package cache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadcastRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller info for mutual registration
	CallerName    string `protobuf:"bytes,1,opt,name=caller_name,json=callerName,proto3" json:"caller_name,omitempty"`
	CallerAddress string `protobuf:"bytes,2,opt,name=caller_address,json=callerAddress,proto3" json:"caller_address,omitempty"`
	CallerVersion string `protobuf:"bytes,3,opt,name=caller_version,json=callerVersion,proto3" json:"caller_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_proto_cache_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastRequest) GetCallerName() string {
	if x != nil {
		return x.CallerName
	}
	return ""
}

func (x *BroadcastRequest) GetCallerAddress() string {
	if x != nil {
		return x.CallerAddress
	}
	return ""
}

func (x *BroadcastRequest) GetCallerVersion() string {
	if x != nil {
		return x.CallerVersion
	}
	return ""
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_proto_cache_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BroadcastResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BroadcastResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_cache_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Healthy          bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	PeerCount        int32                  `protobuf:"varint,2,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	HealthyPeerCount int32                  `protobuf:"varint,3,opt,name=healthy_peer_count,json=healthyPeerCount,proto3" json:"healthy_peer_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_cache_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *HealthCheckResponse) GetHealthyPeerCount() int32 {
	if x != nil {
		return x.HealthyPeerCount
	}
	return 0
}

// CacheValue represents a value that can be one of several types
type CacheValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*CacheValue_StringValue
	//	*CacheValue_IntValue
	//	*CacheValue_FloatValue
	//	*CacheValue_BoolValue
	//	*CacheValue_BytesValue
	Value         isCacheValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheValue) Reset() {
	*x = CacheValue{}
	mi := &file_proto_cache_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheValue) ProtoMessage() {}

func (x *CacheValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheValue.ProtoReflect.Descriptor instead.
func (*CacheValue) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{4}
}

func (x *CacheValue) GetValue() isCacheValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CacheValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*CacheValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *CacheValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*CacheValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *CacheValue) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*CacheValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *CacheValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*CacheValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *CacheValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*CacheValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isCacheValue_Value interface {
	isCacheValue_Value()
}

type CacheValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type CacheValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type CacheValue_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type CacheValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type CacheValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"` // For JSON or raw binary data
}

func (*CacheValue_StringValue) isCacheValue_Value() {}

func (*CacheValue_IntValue) isCacheValue_Value() {}

func (*CacheValue_FloatValue) isCacheValue_Value() {}

func (*CacheValue_BoolValue) isCacheValue_Value() {}

func (*CacheValue_BytesValue) isCacheValue_Value() {}

type SetCacheRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Key               string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value             *CacheValue            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,3,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	FromReplication   bool                   `protobuf:"varint,4,opt,name=from_replication,json=fromReplication,proto3" json:"from_replication,omitempty"` // true if this is a replication from another node (don't re-replicate)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetCacheRequest) Reset() {
	*x = SetCacheRequest{}
	mi := &file_proto_cache_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCacheRequest) ProtoMessage() {}

func (x *SetCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCacheRequest.ProtoReflect.Descriptor instead.
func (*SetCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{5}
}

func (x *SetCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetCacheRequest) GetValue() *CacheValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetCacheRequest) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *SetCacheRequest) GetFromReplication() bool {
	if x != nil {
		return x.FromReplication
	}
	return false
}

type SetCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCacheResponse) Reset() {
	*x = SetCacheResponse{}
	mi := &file_proto_cache_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCacheResponse) ProtoMessage() {}

func (x *SetCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCacheResponse.ProtoReflect.Descriptor instead.
func (*SetCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{6}
}

func (x *SetCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetCacheResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheRequest) Reset() {
	*x = GetCacheRequest{}
	mi := &file_proto_cache_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheRequest) ProtoMessage() {}

func (x *GetCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheRequest.ProtoReflect.Descriptor instead.
func (*GetCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{7}
}

func (x *GetCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Entries       []*CacheEntry          `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheResponse) Reset() {
	*x = GetCacheResponse{}
	mi := &file_proto_cache_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheResponse) ProtoMessage() {}

func (x *GetCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheResponse.ProtoReflect.Descriptor instead.
func (*GetCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{8}
}

func (x *GetCacheResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetCacheResponse) GetEntries() []*CacheEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CacheEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Value             *CacheValue            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,2,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CacheEntry) Reset() {
	*x = CacheEntry{}
	mi := &file_proto_cache_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEntry) ProtoMessage() {}

func (x *CacheEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEntry.ProtoReflect.Descriptor instead.
func (*CacheEntry) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{9}
}

func (x *CacheEntry) GetValue() *CacheValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CacheEntry) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

var File_proto_cache_cache_proto protoreflect.FileDescriptor

const file_proto_cache_cache_proto_rawDesc = "" +
	"\n" +
	"\x17proto/cache/cache.proto\x12\x05cache\"\x81\x01\n" +
	"\x10BroadcastRequest\x12\x1f\n" +
	"\vcaller_name\x18\x01 \x01(\tR\n" +
	"callerName\x12%\n" +
	"\x0ecaller_address\x18\x02 \x01(\tR\rcallerAddress\x12%\n" +
	"\x0ecaller_version\x18\x03 \x01(\tR\rcallerVersion\"[\n" +
	"\x11BroadcastResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x14\n" +
	"\x12HealthCheckRequest\"|\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x02 \x01(\x05R\tpeerCount\x12,\n" +
	"\x12healthy_peer_count\x18\x03 \x01(\x05R\x10healthyPeerCount\"\xc0\x01\n" +
	"\n" +
	"CacheValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x03 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"\xa7\x01\n" +
	"\x0fSetCacheRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.cache.CacheValueR\x05value\x12.\n" +
	"\x13timestamp_unix_nano\x18\x03 \x01(\x03R\x11timestampUnixNano\x12)\n" +
	"\x10from_replication\x18\x04 \x01(\bR\x0ffromReplication\"B\n" +
	"\x10SetCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"#\n" +
	"\x0fGetCacheRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"U\n" +
	"\x10GetCacheResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12+\n" +
	"\aentries\x18\x02 \x03(\v2\x11.cache.CacheEntryR\aentries\"e\n" +
	"\n" +
	"CacheEntry\x12'\n" +
	"\x05value\x18\x01 \x01(\v2\x11.cache.CacheValueR\x05value\x12.\n" +
	"\x13timestamp_unix_nano\x18\x02 \x01(\x03R\x11timestampUnixNano2\x8e\x02\n" +
	"\fCacheService\x12>\n" +
	"\tBroadcast\x12\x17.cache.BroadcastRequest\x1a\x18.cache.BroadcastResponse\x12D\n" +
	"\vHealthCheck\x12\x19.cache.HealthCheckRequest\x1a\x1a.cache.HealthCheckResponse\x12;\n" +
	"\bSetCache\x12\x16.cache.SetCacheRequest\x1a\x17.cache.SetCacheResponse\x12;\n" +
	"\bGetCache\x12\x16.cache.GetCacheRequest\x1a\x17.cache.GetCacheResponseB*Z(github.com/keloran/distcache/proto/cacheb\x06proto3"

var (
	file_proto_cache_cache_proto_rawDescOnce sync.Once
	file_proto_cache_cache_proto_rawDescData []byte
)

func file_proto_cache_cache_proto_rawDescGZIP() []byte {
	file_proto_cache_cache_proto_rawDescOnce.Do(func() {
		file_proto_cache_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cache_cache_proto_rawDesc), len(file_proto_cache_cache_proto_rawDesc)))
	})
	return file_proto_cache_cache_proto_rawDescData
}

var file_proto_cache_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_cache_cache_proto_goTypes = []any{
	(*BroadcastRequest)(nil),    // 0: cache.BroadcastRequest
	(*BroadcastResponse)(nil),   // 1: cache.BroadcastResponse
	(*HealthCheckRequest)(nil),  // 2: cache.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: cache.HealthCheckResponse
	(*CacheValue)(nil),          // 4: cache.CacheValue
	(*SetCacheRequest)(nil),     // 5: cache.SetCacheRequest
	(*SetCacheResponse)(nil),    // 6: cache.SetCacheResponse
	(*GetCacheRequest)(nil),     // 7: cache.GetCacheRequest
	(*GetCacheResponse)(nil),    // 8: cache.GetCacheResponse
	(*CacheEntry)(nil),          // 9: cache.CacheEntry
}
var file_proto_cache_cache_proto_depIdxs = []int32{
	4, // 0: cache.SetCacheRequest.value:type_name -> cache.CacheValue
	9, // 1: cache.GetCacheResponse.entries:type_name -> cache.CacheEntry
	4, // 2: cache.CacheEntry.value:type_name -> cache.CacheValue
	0, // 3: cache.CacheService.Broadcast:input_type -> cache.BroadcastRequest
	2, // 4: cache.CacheService.HealthCheck:input_type -> cache.HealthCheckRequest
	5, // 5: cache.CacheService.SetCache:input_type -> cache.SetCacheRequest
	7, // 6: cache.CacheService.GetCache:input_type -> cache.GetCacheRequest
	1, // 7: cache.CacheService.Broadcast:output_type -> cache.BroadcastResponse
	3, // 8: cache.CacheService.HealthCheck:output_type -> cache.HealthCheckResponse
	6, // 9: cache.CacheService.SetCache:output_type -> cache.SetCacheResponse
	8, // 10: cache.CacheService.GetCache:output_type -> cache.GetCacheResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_cache_cache_proto_init() }
func file_proto_cache_cache_proto_init() {
	if File_proto_cache_cache_proto != nil {
		return
	}
	file_proto_cache_cache_proto_msgTypes[4].OneofWrappers = []any{
		(*CacheValue_StringValue)(nil),
		(*CacheValue_IntValue)(nil),
		(*CacheValue_FloatValue)(nil),
		(*CacheValue_BoolValue)(nil),
		(*CacheValue_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cache_cache_proto_rawDesc), len(file_proto_cache_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cache_cache_proto_goTypes,
		DependencyIndexes: file_proto_cache_cache_proto_depIdxs,
		MessageInfos:      file_proto_cache_cache_proto_msgTypes,
	}.Build()
	File_proto_cache_cache_proto = out.File
	file_proto_cache_cache_proto_goTypes = nil
	file_proto_cache_cache_proto_depIdxs = nil
}
