// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/cache/cache.proto

package cache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadcastRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller info for mutual registration
	CallerName    string `protobuf:"bytes,1,opt,name=caller_name,json=callerName,proto3" json:"caller_name,omitempty"`
	CallerAddress string `protobuf:"bytes,2,opt,name=caller_address,json=callerAddress,proto3" json:"caller_address,omitempty"`
	CallerVersion string `protobuf:"bytes,3,opt,name=caller_version,json=callerVersion,proto3" json:"caller_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_proto_cache_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastRequest) GetCallerName() string {
	if x != nil {
		return x.CallerName
	}
	return ""
}

func (x *BroadcastRequest) GetCallerAddress() string {
	if x != nil {
		return x.CallerAddress
	}
	return ""
}

func (x *BroadcastRequest) GetCallerVersion() string {
	if x != nil {
		return x.CallerVersion
	}
	return ""
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_proto_cache_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BroadcastResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BroadcastResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_cache_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Healthy          bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	PeerCount        int32                  `protobuf:"varint,2,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	HealthyPeerCount int32                  `protobuf:"varint,3,opt,name=healthy_peer_count,json=healthyPeerCount,proto3" json:"healthy_peer_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_cache_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *HealthCheckResponse) GetHealthyPeerCount() int32 {
	if x != nil {
		return x.HealthyPeerCount
	}
	return 0
}

// CacheValue represents any JSON-compatible value
type CacheValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *structpb.Value        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheValue) Reset() {
	*x = CacheValue{}
	mi := &file_proto_cache_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheValue) ProtoMessage() {}

func (x *CacheValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheValue.ProtoReflect.Descriptor instead.
func (*CacheValue) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{4}
}

func (x *CacheValue) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetCacheRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Key               string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value             *CacheValue            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,3,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	FromReplication   bool                   `protobuf:"varint,4,opt,name=from_replication,json=fromReplication,proto3" json:"from_replication,omitempty"` // true if this is a replication from another node (don't re-replicate)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetCacheRequest) Reset() {
	*x = SetCacheRequest{}
	mi := &file_proto_cache_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCacheRequest) ProtoMessage() {}

func (x *SetCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCacheRequest.ProtoReflect.Descriptor instead.
func (*SetCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{5}
}

func (x *SetCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetCacheRequest) GetValue() *CacheValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetCacheRequest) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *SetCacheRequest) GetFromReplication() bool {
	if x != nil {
		return x.FromReplication
	}
	return false
}

type SetCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCacheResponse) Reset() {
	*x = SetCacheResponse{}
	mi := &file_proto_cache_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCacheResponse) ProtoMessage() {}

func (x *SetCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCacheResponse.ProtoReflect.Descriptor instead.
func (*SetCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{6}
}

func (x *SetCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetCacheResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheRequest) Reset() {
	*x = GetCacheRequest{}
	mi := &file_proto_cache_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheRequest) ProtoMessage() {}

func (x *GetCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheRequest.ProtoReflect.Descriptor instead.
func (*GetCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{7}
}

func (x *GetCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Entries       []*CacheEntry          `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheResponse) Reset() {
	*x = GetCacheResponse{}
	mi := &file_proto_cache_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheResponse) ProtoMessage() {}

func (x *GetCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheResponse.ProtoReflect.Descriptor instead.
func (*GetCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{8}
}

func (x *GetCacheResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetCacheResponse) GetEntries() []*CacheEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CacheEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Value             *CacheValue            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,2,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CacheEntry) Reset() {
	*x = CacheEntry{}
	mi := &file_proto_cache_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEntry) ProtoMessage() {}

func (x *CacheEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEntry.ProtoReflect.Descriptor instead.
func (*CacheEntry) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{9}
}

func (x *CacheEntry) GetValue() *CacheValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CacheEntry) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

type SyncCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCacheRequest) Reset() {
	*x = SyncCacheRequest{}
	mi := &file_proto_cache_cache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCacheRequest) ProtoMessage() {}

func (x *SyncCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCacheRequest.ProtoReflect.Descriptor instead.
func (*SyncCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{10}
}

type SyncCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SyncCacheEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalKeys     int32                  `protobuf:"varint,2,opt,name=total_keys,json=totalKeys,proto3" json:"total_keys,omitempty"`
	TotalEntries  int32                  `protobuf:"varint,3,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCacheResponse) Reset() {
	*x = SyncCacheResponse{}
	mi := &file_proto_cache_cache_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCacheResponse) ProtoMessage() {}

func (x *SyncCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCacheResponse.ProtoReflect.Descriptor instead.
func (*SyncCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{11}
}

func (x *SyncCacheResponse) GetEntries() []*SyncCacheEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *SyncCacheResponse) GetTotalKeys() int32 {
	if x != nil {
		return x.TotalKeys
	}
	return 0
}

func (x *SyncCacheResponse) GetTotalEntries() int32 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

type SyncCacheEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []*CacheEntry          `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCacheEntry) Reset() {
	*x = SyncCacheEntry{}
	mi := &file_proto_cache_cache_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCacheEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCacheEntry) ProtoMessage() {}

func (x *SyncCacheEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_cache_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCacheEntry.ProtoReflect.Descriptor instead.
func (*SyncCacheEntry) Descriptor() ([]byte, []int) {
	return file_proto_cache_cache_proto_rawDescGZIP(), []int{12}
}

func (x *SyncCacheEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SyncCacheEntry) GetValues() []*CacheEntry {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_proto_cache_cache_proto protoreflect.FileDescriptor

const file_proto_cache_cache_proto_rawDesc = "" +
	"\n" +
	"\x17proto/cache/cache.proto\x12\x05cache\x1a\x1cgoogle/protobuf/struct.proto\"\x81\x01\n" +
	"\x10BroadcastRequest\x12\x1f\n" +
	"\vcaller_name\x18\x01 \x01(\tR\n" +
	"callerName\x12%\n" +
	"\x0ecaller_address\x18\x02 \x01(\tR\rcallerAddress\x12%\n" +
	"\x0ecaller_version\x18\x03 \x01(\tR\rcallerVersion\"[\n" +
	"\x11BroadcastResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x14\n" +
	"\x12HealthCheckRequest\"|\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x02 \x01(\x05R\tpeerCount\x12,\n" +
	"\x12healthy_peer_count\x18\x03 \x01(\x05R\x10healthyPeerCount\":\n" +
	"\n" +
	"CacheValue\x12,\n" +
	"\x05value\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\xa7\x01\n" +
	"\x0fSetCacheRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.cache.CacheValueR\x05value\x12.\n" +
	"\x13timestamp_unix_nano\x18\x03 \x01(\x03R\x11timestampUnixNano\x12)\n" +
	"\x10from_replication\x18\x04 \x01(\bR\x0ffromReplication\"B\n" +
	"\x10SetCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"#\n" +
	"\x0fGetCacheRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"U\n" +
	"\x10GetCacheResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12+\n" +
	"\aentries\x18\x02 \x03(\v2\x11.cache.CacheEntryR\aentries\"e\n" +
	"\n" +
	"CacheEntry\x12'\n" +
	"\x05value\x18\x01 \x01(\v2\x11.cache.CacheValueR\x05value\x12.\n" +
	"\x13timestamp_unix_nano\x18\x02 \x01(\x03R\x11timestampUnixNano\"\x12\n" +
	"\x10SyncCacheRequest\"\x88\x01\n" +
	"\x11SyncCacheResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.cache.SyncCacheEntryR\aentries\x12\x1d\n" +
	"\n" +
	"total_keys\x18\x02 \x01(\x05R\ttotalKeys\x12#\n" +
	"\rtotal_entries\x18\x03 \x01(\x05R\ftotalEntries\"M\n" +
	"\x0eSyncCacheEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x06values\x18\x02 \x03(\v2\x11.cache.CacheEntryR\x06values2\xce\x02\n" +
	"\fCacheService\x12>\n" +
	"\tBroadcast\x12\x17.cache.BroadcastRequest\x1a\x18.cache.BroadcastResponse\x12D\n" +
	"\vHealthCheck\x12\x19.cache.HealthCheckRequest\x1a\x1a.cache.HealthCheckResponse\x12;\n" +
	"\bSetCache\x12\x16.cache.SetCacheRequest\x1a\x17.cache.SetCacheResponse\x12;\n" +
	"\bGetCache\x12\x16.cache.GetCacheRequest\x1a\x17.cache.GetCacheResponse\x12>\n" +
	"\tSyncCache\x12\x17.cache.SyncCacheRequest\x1a\x18.cache.SyncCacheResponseB*Z(github.com/keloran/distcache/proto/cacheb\x06proto3"

var (
	file_proto_cache_cache_proto_rawDescOnce sync.Once
	file_proto_cache_cache_proto_rawDescData []byte
)

func file_proto_cache_cache_proto_rawDescGZIP() []byte {
	file_proto_cache_cache_proto_rawDescOnce.Do(func() {
		file_proto_cache_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cache_cache_proto_rawDesc), len(file_proto_cache_cache_proto_rawDesc)))
	})
	return file_proto_cache_cache_proto_rawDescData
}

var file_proto_cache_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_cache_cache_proto_goTypes = []any{
	(*BroadcastRequest)(nil),    // 0: cache.BroadcastRequest
	(*BroadcastResponse)(nil),   // 1: cache.BroadcastResponse
	(*HealthCheckRequest)(nil),  // 2: cache.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: cache.HealthCheckResponse
	(*CacheValue)(nil),          // 4: cache.CacheValue
	(*SetCacheRequest)(nil),     // 5: cache.SetCacheRequest
	(*SetCacheResponse)(nil),    // 6: cache.SetCacheResponse
	(*GetCacheRequest)(nil),     // 7: cache.GetCacheRequest
	(*GetCacheResponse)(nil),    // 8: cache.GetCacheResponse
	(*CacheEntry)(nil),          // 9: cache.CacheEntry
	(*SyncCacheRequest)(nil),    // 10: cache.SyncCacheRequest
	(*SyncCacheResponse)(nil),   // 11: cache.SyncCacheResponse
	(*SyncCacheEntry)(nil),      // 12: cache.SyncCacheEntry
	(*structpb.Value)(nil),      // 13: google.protobuf.Value
}
var file_proto_cache_cache_proto_depIdxs = []int32{
	13, // 0: cache.CacheValue.value:type_name -> google.protobuf.Value
	4,  // 1: cache.SetCacheRequest.value:type_name -> cache.CacheValue
	9,  // 2: cache.GetCacheResponse.entries:type_name -> cache.CacheEntry
	4,  // 3: cache.CacheEntry.value:type_name -> cache.CacheValue
	12, // 4: cache.SyncCacheResponse.entries:type_name -> cache.SyncCacheEntry
	9,  // 5: cache.SyncCacheEntry.values:type_name -> cache.CacheEntry
	0,  // 6: cache.CacheService.Broadcast:input_type -> cache.BroadcastRequest
	2,  // 7: cache.CacheService.HealthCheck:input_type -> cache.HealthCheckRequest
	5,  // 8: cache.CacheService.SetCache:input_type -> cache.SetCacheRequest
	7,  // 9: cache.CacheService.GetCache:input_type -> cache.GetCacheRequest
	10, // 10: cache.CacheService.SyncCache:input_type -> cache.SyncCacheRequest
	1,  // 11: cache.CacheService.Broadcast:output_type -> cache.BroadcastResponse
	3,  // 12: cache.CacheService.HealthCheck:output_type -> cache.HealthCheckResponse
	6,  // 13: cache.CacheService.SetCache:output_type -> cache.SetCacheResponse
	8,  // 14: cache.CacheService.GetCache:output_type -> cache.GetCacheResponse
	11, // 15: cache.CacheService.SyncCache:output_type -> cache.SyncCacheResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_cache_cache_proto_init() }
func file_proto_cache_cache_proto_init() {
	if File_proto_cache_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cache_cache_proto_rawDesc), len(file_proto_cache_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cache_cache_proto_goTypes,
		DependencyIndexes: file_proto_cache_cache_proto_depIdxs,
		MessageInfos:      file_proto_cache_cache_proto_msgTypes,
	}.Build()
	File_proto_cache_cache_proto = out.File
	file_proto_cache_cache_proto_goTypes = nil
	file_proto_cache_cache_proto_depIdxs = nil
}
